			<div id="poststuff" class="flir">
      	<div class="postbox close-me">
      	<h3><?php _e('FLIR Settings',"FLIR"); ?>: </h3>
      	<div class="inside">
					<form action="?page=FLIR" method="post" id="flir_settings" name="flir_settings">
					<table>
					<tr><td valign="top"><strong><?php _e('Clear Cache',"FLIR"); ?>: </strong></td><td valign="top">
							<input type="checkbox" name="clear_cache" value="1" />
						</td><td valign="top"><small><?php _e('This will immediately clear the FLIR cache',"FLIR"); ?></small></td>
					</tr>
					<tr><td valign="top"><strong><?php _e('Reinitialize FLIR',"FLIR"); ?>: </strong></td><td valign="top">
							<input type="checkbox" name="reinit_flir" value="1" />
						</td><td valign="top"><small><?php _e('This will immediately clear the FLIR cache, and reinitialize the plugin deleting all existing settings',"FLIR"); ?></small></td>
					</tr>
					</table>
					<p class="submit"><input type="submit" class="btn" name="save" style="padding:5px 30px 5px 30px;" value="<?php _e('Update FLIR Settings',"FLIR"); ?>" /></p>
					<input type="hidden" name="action" value="action" /><input type="hidden" name="sub" value="settings" />
         </form>
			</div>
			</div>
			</div>
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" style="float:right"> <input name="cmd" type="hidden" value="_s-xclick" /> <input alt="PayPal - The safer, easier way to pay online!" name="submit" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" type="image" /> <img src="https://www.paypal.com/en_US/i/scr/pixel.gif" border="0" alt="" width="1" height="1" />

<input name="encrypted" type="hidden" value="-----BEGIN PKCS7-----MIIHZwYJKoZIhvcNAQcEoIIHWDCCB1QCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCeU42q5Ibd+xNJ/MHqK3KD51BUwD5hpFHO9bNt7bE5o14ipfv7wKgZgRbhIRCuJKHv3Gt4xMIZhVCcfdQagWkGpSAnlmi5AaNX51l6vRZkLwcqQklcoBYpmkaRX8hFIWj3V0vxI1Oh6Al2yoXCD/gTMMq/C4ft2pKDd3d1n4Yq9TELMAkGBSsOAwIaBQAwgeQGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQINHAikH9MXQeAgcA9bLAq2Gt3mXyellAI96YeMCACD07fQwzpJUkyqZsSMYIkK3UvX3JSpU01mncTzYEe1XXKB7dsApYaZKIb8ezAdMZzBsB6s9CpUvSttN/x/SssFqLvfYqSkFRPd0qHRmNtfMzsEhk5+AAz2yNAlvA6bppiaZ8WQh5pFBIGbJaxc5Y4uFDpmyF+468irP4gBcni228EmDAPnqbcRHgfvTGUngWMvGbgFTutCY9foBZAGao6Mew3F9YoUoijUy2gF3mgggOHMIIDgzCCAuygAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wHhcNMDQwMjEzMTAxMzE1WhcNMzUwMjEzMTAxMzE1WjCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMFHTt38RMxLXJyO2SmS+Ndl72T7oKJ4u4uw+6awntALWh03PewmIJuzbALScsTS4sZoS1fKciBGoh11gIfHzylvkdNe/hJl66/RGqrj5rFb08sAABNTzDTiqqNpJeBsYs/c2aiGozptX2RlnBktH+SUNpAajW724Nv2Wvhif6sFAgMBAAGjge4wgeswHQYDVR0OBBYEFJaffLvGbxe9WT9S1wob7BDWZJRrMIG7BgNVHSMEgbMwgbCAFJaffLvGbxe9WT9S1wob7BDWZJRroYGUpIGRMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbYIBADAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAIFfOlaagFrl71+jq6OKidbWFSE+Q4FqROvdgIONth+8kSK//Y/4ihuE4Ymvzn5ceE3S/iBSQQMjyvb+s2TWbQYDwcp129OPIbD9epdr4tJOUNiSojw7BHwYRiPh58S1xGlFgHFXwrEBb3dgNbMUa+u4qectsMAXpVHnD9wIyfmHMYIBmjCCAZYCAQEwgZQwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tAgEAMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0wODA4MDgxODM4MDZaMCMGCSqGSIb3DQEJBDEWBBQILNsL1gyBAP7CukBqRsPdm8yovjANBgkqhkiG9w0BAQEFAASBgA7d1py7zOhW/khToG2Hw1cgNkLwOKKZTtNM8DJUOEHgmBHQ7pOtEesbQcCGYjz2R8pjPnFJ/EwTZSM5h0ftkK9xo9iN57O9JMMyUuLkpuL9ppe7L6OhXq4+frw7hPO+IkxGn/1CD1Fkh+hPqVA/Ea+IxxPvKWUlH6BLyl5vkOIM-----END PKCS7-----&lt;br /&gt;" />
</form><h4><?php _e('Thank you for downloading and installing FLIR for WordPress',"FLIR"); ?></h4>
			<small><?php _e('Like many developers I spend a lot of my spare time working on WordPress plugins and themes and any donation to the cause is appreciated.  I know a lot of other developers do the same and I try to donate to them whenever I can.  As a developer I greatly appreciate any donation you can make to help support further development of quality plugins and themes for WordPress.  In keeping with the name of this my site <a href="http://www.23systems.net">23Systems</a> a minimum donation of $2.30 is encouraged but I\'ll gladly accept whatever you feel comfortable with.  <em>You have my sincere thanks and appreciation</em>.',"FLIR"); ?></small>