<?php
/**
* Facelift Image Replacement v2.0b3
* Auto-Generated by FLIR for WordPress at 2010-06-29 19:28:56
* 
* Facelift was written and is maintained by Cory Mawhorter.
* It is available from http://facelift.mawhorter.net/
*/
define('ALLOWED_DOMAIN', false); // ex: 'example.com', 'subdomain.domain.com', '.allsubdomains.com', false disabled
define('UNKNOWN_FONT_SIZE', 16); // in pixels

define('CACHE_CLEANUP_FREQ', -1); // -1 disable, 1 everytime, 10 would be about 1 in 10 times this script runs (higher number decreases frequency)
define('CACHE_KEEP_TIME', 604800); // 604800: 7 days
define('CACHE_SINGLE_DIR', false); // don't create subdirs to store cached files (good for small sites)

define('FONT_DISCOVERY', false);

define('CACHE_DIR', 'cache');
define('FONTS_DIR', 'fonts');
define('PLUGIN_DIR', 'plugins');
define('RENDER_PLUGIN_DIR', PLUGIN_DIR.'/render');
define('PREPROC_PLUGIN_DIR', PLUGIN_DIR.'/pre');
define('POSTPROC_AUTORUN', 'supercache');
define('POSTPROC_PLUGIN_DIR', PLUGIN_DIR.'/post');

define('HBOUNDS_TEXT', 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz[]{}()_'); // see http://facelift.mawhorter.net/docs/

define('IM_EXEC_PATH', '/usr/bin/');  // ImageMagick binaries path

/**
* Each font you want to use should have an entry in the fonts array.
* FLIR for WordPress should generate this based on the fonts in your
* wp-content/plugins/facelift-image-replacement/facelift/fonts dir
* 
* @var mixed
*/
$fonts = array();
$fonts['baarssophia'] 	= 'baars_sophia.ttf'; // baarssophia 
$fonts['bluehighwaycond'] 	= 'blue_highway_cond.ttf'; // bluehighwaycond 
$fonts['bluehighwayregular'] 	= 'Blue_Highway_regular.ttf'; // bluehighwayregular 
$fonts['comt'] 	= 'com4t.ttf'; // comt 
$fonts['deliciousroman'] 	= 'Delicious_Roman.otf'; // deliciousroman 
$fonts['diavlobook'] 	= 'Diavlo_Book.otf'; // diavlobook 
$fonts['fontinregular'] 	= 'Fontin_Regular.ttf'; // fontinregular 
$fonts['hoperound'] 	= 'HopeRound.ttf'; // hoperound 
$fonts['lidostf'] 	= 'LidoSTF.otf'; // lidostf 
$fonts['marlonbook'] 	= 'Marlon_book.ttf'; // marlonbook 
$fonts['qlassiktb'] 	= 'Qlassik_TB.otf'; // qlassiktb 
/**
* The font will default to the following (put your most common font here).
* 
* @var mixed
*/
$fonts['default'] 	= 'Qlassik_TB.otf';

// pipe-separated list of processing plugins to autorun
// modify settings by including them in querystring style
define('PREPROC_AUTORUN', false);
define('POSTPROC_AUTORUN', false);
?>
